version: '3.7'

services:
  app:
    container_name: event_app
    build: .
    volumes:
      - db-volume:/usr/app/src/main/resources/db
    ports:
      - "8080:8080"
    restart: always

volumes:
  db-volume: